

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Roberto
 */
public class Programa extends javax.swing.JFrame {

    /**
     * Creates new form Programa
     */
    public Programa() {
        initComponents();
        modeloTabla = (DefaultTableModel) this.jTab_PRODUCTOS.getModel();
    }

    DefaultTableModel modeloTabla;
    boolean AgregarMásProductos = false;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jText_Nombre = new javax.swing.JTextField();
        jSpinn_ID = new javax.swing.JSpinner();
        jButt_AGREGARPRODUCTO = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jText_DES = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jText_PRECIO = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButt_BUSCARP = new javax.swing.JButton();
        jSpinn_IDB = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        jLab_POSICIÓN = new javax.swing.JLabel();
        jButt_LIMPIARAG = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jText_NM = new javax.swing.JTextField();
        jSpinn_BUSCAR = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jText_DM = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jText_PM = new javax.swing.JTextField();
        jButt_ACTUALIZAR = new javax.swing.JButton();
        jButt_BORRAR = new javax.swing.JButton();
        jButt_ORDENAR = new javax.swing.JButton();
        jRadioButt_ASC = new javax.swing.JRadioButton();
        jRadioButt_DES = new javax.swing.JRadioButton();
        jButt_LIMPIARAC = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTab_PRODUCTOS = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButt_SALIR = new javax.swing.JButton();
        jButt_REINICIAR = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TIENDA DE ROBERTO GRIJALVA");

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel6.setBackground(new java.awt.Color(204, 204, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setPreferredSize(new java.awt.Dimension(250, 252));

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        jLabel1.setText("INGRESAR PRODUCTOS:");

        jLabel2.setText("ID:");

        jLabel3.setText("Nombre:");

        jSpinn_ID.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jButt_AGREGARPRODUCTO.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jButt_AGREGARPRODUCTO.setText("Agregar");
        jButt_AGREGARPRODUCTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButt_AGREGARPRODUCTOActionPerformed(evt);
            }
        });

        jLabel4.setText("Descripción:");

        jLabel5.setText("Precio:");

        jLabel11.setText("Producto a buscar:");

        jButt_BUSCARP.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jButt_BUSCARP.setText("Buscar");
        jButt_BUSCARP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButt_BUSCARPActionPerformed(evt);
            }
        });

        jSpinn_IDB.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel13.setText("Posición:");

        jButt_LIMPIARAG.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jButt_LIMPIARAG.setText("Limpiar");
        jButt_LIMPIARAG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButt_LIMPIARAGActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jText_Nombre)
                    .addComponent(jText_DES)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jText_PRECIO))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jButt_BUSCARP)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLab_POSICIÓN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 3, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinn_ID))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButt_AGREGARPRODUCTO, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSpinn_IDB)
                            .addComponent(jButt_LIMPIARAG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jSpinn_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText_DES, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jText_PRECIO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButt_AGREGARPRODUCTO)
                    .addComponent(jButt_LIMPIARAG))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jSpinn_IDB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButt_BUSCARP)
                        .addComponent(jLabel13))
                    .addComponent(jLab_POSICIÓN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(255, 153, 153));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.setPreferredSize(new java.awt.Dimension(250, 252));

        jLabel6.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        jLabel6.setText("modificar PRODUCTOS:");

        jLabel7.setText("ID:");

        jLabel8.setText("Nombre:");

        jSpinn_BUSCAR.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel9.setText("Descripción:");

        jLabel10.setText("Precio:");

        jButt_ACTUALIZAR.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jButt_ACTUALIZAR.setText("Actualizar");
        jButt_ACTUALIZAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButt_ACTUALIZARActionPerformed(evt);
            }
        });

        jButt_BORRAR.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jButt_BORRAR.setText("BORRAR");
        jButt_BORRAR.setEnabled(false);
        jButt_BORRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButt_BORRARActionPerformed(evt);
            }
        });

        jButt_ORDENAR.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jButt_ORDENAR.setText("Ordenar");
        jButt_ORDENAR.setEnabled(false);
        jButt_ORDENAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButt_ORDENARActionPerformed(evt);
            }
        });

        jRadioButt_ASC.setBackground(new java.awt.Color(255, 153, 153));
        buttonGroup1.add(jRadioButt_ASC);
        jRadioButt_ASC.setText("Ascendente");
        jRadioButt_ASC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButt_ASCActionPerformed(evt);
            }
        });

        jRadioButt_DES.setBackground(new java.awt.Color(255, 153, 153));
        buttonGroup1.add(jRadioButt_DES);
        jRadioButt_DES.setText("Descendente");
        jRadioButt_DES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButt_DESActionPerformed(evt);
            }
        });

        jButt_LIMPIARAC.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jButt_LIMPIARAC.setText("Limpiar");
        jButt_LIMPIARAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButt_LIMPIARACActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jText_PM, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jText_DM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jText_NM, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSpinn_BUSCAR, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButt_BORRAR))
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(jButt_ACTUALIZAR, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButt_LIMPIARAC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(8, 8, 8))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                .addComponent(jRadioButt_ASC)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButt_DES))
                            .addComponent(jButt_ORDENAR, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jSpinn_BUSCAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButt_BORRAR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText_NM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText_DM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jText_PM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(12, 12, 12)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButt_ACTUALIZAR)
                    .addComponent(jButt_LIMPIARAC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButt_ASC)
                    .addComponent(jRadioButt_DES))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButt_ORDENAR)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 51, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTab_PRODUCTOS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE", "DESCRIPCIÓN", "PRECIO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTab_PRODUCTOS);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 816, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButt_SALIR.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jButt_SALIR.setText("SALIR");
        jButt_SALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButt_SALIRActionPerformed(evt);
            }
        });

        jButt_REINICIAR.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jButt_REINICIAR.setText("Reiniciar");
        jButt_REINICIAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButt_REINICIARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButt_REINICIAR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButt_SALIR)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButt_SALIR)
                    .addComponent(jButt_REINICIAR)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 683, Short.MAX_VALUE)
                    .addComponent(jLabel14)
                    .addGap(0, 683, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel14)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButt_AGREGARPRODUCTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButt_AGREGARPRODUCTOActionPerformed
        try{
            
            if(this.jText_Nombre.getText().isEmpty() || this.jText_DES.getText().isEmpty() || this.jText_PRECIO.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Falta información en algunos campos!");
            }else{
                this.jButt_BORRAR.setEnabled(true);
                if(AgregarMásProductos == true){
                    
                    int dato = 0;
                    boolean agregar = true;
                    for(int i = 0; i < modeloTabla.getRowCount(); i++){
                        dato = Integer.parseInt(this.jTab_PRODUCTOS.getValueAt(i, 0).toString());
                        if(Integer.parseInt(this.jSpinn_ID.getValue().toString()) == dato){
                            agregar = false;
                            JOptionPane.showMessageDialog(null, "Ya existe un producto con este ID: "+this.jSpinn_ID.getValue()+". Por favor seleccione otro.");
                        }
                    }
                    
//                    if(Integer.parseInt(this.jSpinn_ID.getValue().toString()) == dato){
//                            JOptionPane.showMessageDialog(null, "Ya existe un producto con este ID: "+this.jSpinn_ID.getValue()+". Por favor seleccione otro.");
//                        }else{
                    if(agregar == true && AgregarMásProductos == true){  
                     modeloTabla.insertRow(modeloTabla.getRowCount(), new Object[]{
                     this.jSpinn_ID.getValue(), this.jText_Nombre.getText(),
                     this.jText_DES.getText(), this.jText_PRECIO.getText()});
                    }   
                }else if(AgregarMásProductos == false){
                 modeloTabla.insertRow(modeloTabla.getRowCount(), new Object[]{
                 this.jSpinn_ID.getValue(), this.jText_Nombre.getText(),
                 this.jText_DES.getText(), this.jText_PRECIO.getText()});
                 AgregarMásProductos = true;
                }
            } 
        }catch(RuntimeException ex){
            
        }
    }//GEN-LAST:event_jButt_AGREGARPRODUCTOActionPerformed

    private void jButt_ACTUALIZARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButt_ACTUALIZARActionPerformed
        try{
            if(this.jText_NM.getText().isEmpty() || this.jText_DM.getText().isEmpty() || this.jText_PM.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Falta información en algunos campos!");
            }else{
                boolean modificar = false;
              int Clave = Integer.parseInt(this.jSpinn_BUSCAR.getValue().toString());
              for(int i = 0; i < modeloTabla.getRowCount(); i++){
                int Cx = Integer.parseInt(this.jTab_PRODUCTOS.getValueAt(i, 0).toString());
                if(Clave == Cx){
                     modificar = true;
                     modeloTabla.removeRow(i);
                    }
                }
                if(modificar == true){
                    modeloTabla.insertRow(modeloTabla.getRowCount(), new Object[]{
                    this.jSpinn_BUSCAR.getValue(), this.jText_NM.getText(),
                    this.jText_DM.getText(),this.jText_PM.getText()});
                }else{
                    JOptionPane.showMessageDialog(null, "La clave seleccionada no coincide con ningúna.");
                }
            }
        }catch(RuntimeException ex){
            
        }
    }//GEN-LAST:event_jButt_ACTUALIZARActionPerformed

    private void jButt_BORRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButt_BORRARActionPerformed
        try{
            if(this.jTab_PRODUCTOS.getRowCount() == 0){
                JOptionPane.showMessageDialog(null, "No hay ningún producto en la lista");
            }
            int Clave = Integer.parseInt(this.jSpinn_BUSCAR.getValue().toString());
            for(int i = 0 ; i < modeloTabla.getRowCount(); i++){
                int Cx = Integer.parseInt(this.jTab_PRODUCTOS.getValueAt(i, 0).toString());
                if(Clave == Cx){
                    int r = JOptionPane.showConfirmDialog(this, "¿Seguro que desea ELIMINAR el producto?","Borrar",JOptionPane.YES_OPTION, JOptionPane.WARNING_MESSAGE);
                    if(r == JOptionPane.YES_OPTION){
                        modeloTabla.removeRow(i);
                    }
                }
            }
        }catch(RuntimeException ex){
            
        }
    }//GEN-LAST:event_jButt_BORRARActionPerformed

    private void jButt_SALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButt_SALIRActionPerformed
        try{
            int r = JOptionPane.showConfirmDialog(this,"¿Realmente desea salir?", "Salir",JOptionPane.YES_OPTION, JOptionPane.ERROR_MESSAGE);

            if( r == JOptionPane.YES_OPTION){
                System.exit(0);
            }
        }catch(RuntimeException ex){
            
        }
    }//GEN-LAST:event_jButt_SALIRActionPerformed

    private void jButt_ORDENARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButt_ORDENARActionPerformed
        try{
            
            int vec[] = new int[modeloTabla.getRowCount()];
            
            Número comp = new Número();
            comp.n = 0;
            
            Número inter = new Número();
            inter.n = 0;

            if(this.jRadioButt_ASC.isSelected()){
                Métodos.quicksort(modeloTabla, 0, vec.length-1, true);
            }else if(this.jRadioButt_DES.isSelected()){
                Métodos.quicksort(modeloTabla, 0, vec.length-1, false);
            }
        }catch(RuntimeException ex){
            
        }
    }//GEN-LAST:event_jButt_ORDENARActionPerformed

    private void jButt_BUSCARPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButt_BUSCARPActionPerformed
        try{
            int []vec = new int[this.jTab_PRODUCTOS.getRowCount()];
            
            for(int i = 0; i < vec.length; i++){
                vec[i] = Integer.parseInt(modeloTabla.getValueAt(i, 0).toString());
            }
            
            Número p = new Número();
            p.n = 0;
            
            Boolean b = new Boolean();
            b.b = false;
            
            Métodos.Binario(vec, Integer.parseInt(this.jSpinn_IDB.getValue().toString()), p, b);
            
            if(b.b == true){
                this.jLab_POSICIÓN.setText(""+(p.n+1));
            }else if(b.b == false){
                JOptionPane.showMessageDialog(null, "No existe un producto con este ID: "+this.jSpinn_IDB.getValue());
            }
        }catch(RuntimeException e){
            
        }
    }//GEN-LAST:event_jButt_BUSCARPActionPerformed

    private void jButt_LIMPIARAGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButt_LIMPIARAGActionPerformed
        this.jText_DES.setText(null);
        this.jText_Nombre.setText(null);
        this.jText_PRECIO.setText(null);
    }//GEN-LAST:event_jButt_LIMPIARAGActionPerformed

    private void jButt_LIMPIARACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButt_LIMPIARACActionPerformed
        this.jText_DM.setText(null);
        this.jText_NM.setText(null);
        this.jText_PM.setText(null);
    }//GEN-LAST:event_jButt_LIMPIARACActionPerformed

    private void jRadioButt_ASCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButt_ASCActionPerformed
        if(this.jRadioButt_ASC.isSelected()){
            this.jButt_ORDENAR.setEnabled(true);
        }
    }//GEN-LAST:event_jRadioButt_ASCActionPerformed

    private void jRadioButt_DESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButt_DESActionPerformed
        if(this.jRadioButt_DES.isSelected()){
            this.jButt_ORDENAR.setEnabled(true);
        }
    }//GEN-LAST:event_jRadioButt_DESActionPerformed

    private void jButt_REINICIARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButt_REINICIARActionPerformed
        int r = JOptionPane.showConfirmDialog(this, "Seguro que desea REINICIAR?"
                + "Se perderán todos los productos","REINICIAR",JOptionPane.YES_OPTION);
        if(r == JOptionPane.YES_OPTION){
        modeloTabla.setRowCount(0);
        this.jText_DM.setText(null);
        this.jText_NM.setText(null);
        this.jText_PM.setText(null);
        this.jText_DES.setText(null);
        this.jText_Nombre.setText(null);
        this.jText_PRECIO.setText(null);
        this.jSpinn_BUSCAR.setValue(1);
        this.jSpinn_ID.setValue(1);
        this.jSpinn_IDB.setValue(1);
        this.jButt_ORDENAR.setEnabled(false);
        this.jButt_BORRAR.setEnabled(false);
        }   
    }//GEN-LAST:event_jButt_REINICIARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Programa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButt_ACTUALIZAR;
    private javax.swing.JButton jButt_AGREGARPRODUCTO;
    private javax.swing.JButton jButt_BORRAR;
    private javax.swing.JButton jButt_BUSCARP;
    private javax.swing.JButton jButt_LIMPIARAC;
    private javax.swing.JButton jButt_LIMPIARAG;
    private javax.swing.JButton jButt_ORDENAR;
    private javax.swing.JButton jButt_REINICIAR;
    private javax.swing.JButton jButt_SALIR;
    private javax.swing.JLabel jLab_POSICIÓN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRadioButt_ASC;
    private javax.swing.JRadioButton jRadioButt_DES;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinn_BUSCAR;
    private javax.swing.JSpinner jSpinn_ID;
    private javax.swing.JSpinner jSpinn_IDB;
    private javax.swing.JTable jTab_PRODUCTOS;
    private javax.swing.JTextField jText_DES;
    private javax.swing.JTextField jText_DM;
    private javax.swing.JTextField jText_NM;
    private javax.swing.JTextField jText_Nombre;
    private javax.swing.JTextField jText_PM;
    private javax.swing.JTextField jText_PRECIO;
    // End of variables declaration//GEN-END:variables
}
